# Generated by Django 4.2.2 on 2023-08-03 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellsFargoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wells_fargo_app', models.CharField(max_length=1000, verbose_name='Aplicación')),
                ('transaction_uuid', models.CharField(max_length=100, verbose_name='UUID de transacción')),
                ('status', models.CharField(choices=[('pending', 'pendiente'), ('completed', 'completado'), ('rejected', 'rechazado')], default='pending', max_length=15, verbose_name='Estado')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'wellsfargo_payment',
                'ordering': ('-datetime',),
                'permissions': (('add_wellsfargopayment', 'Adicionar pagos de Wells Fargo'), ('change_wellsfargopayment', 'Editar pagos de Wells Fargo'), ('view_wellsfargopayment', 'Ver pagos de Wells Fargo'), ('delete_wellsfargopayment', 'Eliminar pagos de Wells Fargo')),
                'default_permissions': [],
            },
        ),
    ]
