# Generated by Django 4.2.2 on 2023-08-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wellsfargopayment',
            options={'default_permissions': [], 'ordering': ('-datetime',), 'permissions': (('add_wellsfargopayment', 'Adicionar pagos de Wells Fargo'), ('change_wellsfargopayment', 'Editar pagos de Wells Fargo'), ('view_wellsfargopayment', 'Ver pagos de Wells Fargo'), ('delete_wellsfargopayment', 'Eliminar pagos de Wells Fargo')), 'verbose_name': 'Wells Fargo', 'verbose_name_plural': 'Wells Fargo'},
        ),
    ]
