# Generated by Django 4.2.2 on 2023-08-09 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_alter_wellsfargopayment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellsfargopayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='wellsfargopayment',
            name='wells_fargo_app',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Aplicación'),
        ),
    ]
