# Generated by Django 4.2.2 on 2023-08-09 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('payments', '0003_alter_wellsfargopayment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellsfargopayment',
            name='wells_fargo_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='Aplicación'),
        ),
    ]
