# Generated by Django 4.2.2 on 2023-08-11 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_alter_wellsfargopayment_wells_fargo_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wellsfargopayment',
            options={'default_permissions': [], 'ordering': ('-datetime',), 'permissions': (('add_wellsfargopayment', 'Adicionar pagos de Wells Fargo'), ('change_wellsfargopayment', 'Editar pagos de Wells Fargo'), ('view_wellsfargopayment', 'Ver pagos de Wells Fargo'), ('delete_wellsfargopayment', 'Eliminar pagos de Wells Fargo')), 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.CreateModel(
            name='SquaresPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=100, null=True, verbose_name='ID de transacción')),
                ('source_id', models.CharField(max_length=100, null=True, verbose_name='Fuente de Pago')),
                ('amount', models.IntegerField(null=True, verbose_name='Cantidad de dinero a pagar')),
                ('currency', models.CharField(max_length=20, null=True, verbose_name='Tipo de Moneda')),
                ('customer_id', models.CharField(max_length=100, null=True, verbose_name='Cuenta de Destino')),
                ('reference_id', models.CharField(max_length=100, null=True, verbose_name='ID Único de Tranferencia')),
                ('status', models.CharField(choices=[('pending', 'pendiente'), ('completed', 'completado'), ('rejected', 'rechazado')], default='pending', max_length=15, verbose_name='Estado')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('square_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='Aplicación')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'squares_payment',
                'ordering': ('-datetime',),
                'permissions': (('add_squarespayment', 'Adicionar pagos de Square'), ('change_squarespayment', 'Editar pagos de Square'), ('view_squarespayment', 'Ver pagos de Square'), ('delete_squarespayment', 'Eliminar pagos de Square')),
                'default_permissions': [],
            },
        ),
    ]
