@ -0,0 +1,18 @@
# Generated by Django 4.2.2 on 2023-09-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_wellsfargopayment_options_squarespayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squarespayment',
            name='amount',
            field=models.FloatField(null=True, verbose_name='Cantidad de dinero a pagar'),
        ),
    ]