# Generated by Django 4.2.2 on 2023-09-22 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0006_alter_squarespayment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankOfAmericaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uuid', models.CharField(max_length=100, verbose_name='UUID de transacción')),
                ('status', models.CharField(choices=[('pending', 'pendiente'), ('completed', 'completado'), ('rejected', 'rechazado')], default='pending', max_length=15, verbose_name='Estado')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('bank_of_america_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='Aplicación')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'bankofamerica_payment',
                'ordering': ('-datetime',),
                'permissions': (('add_bankofamericapayment', 'Adicionar pagos de Bank of America'), ('change_bankofamericapayment', 'Editar pagos de Bank of America'), ('view_bankofamericapayment', 'Ver pagos de Bank of America'), ('delete_bankofamericapayment', 'Eliminar pagos de Bank of America')),
                'default_permissions': [],
            },
        ),
    ]
