# Generated by Django 4.2.2 on 2023-08-03 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth2_provider', '0005_alter_accesstoken_user_alter_application_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellsFargoApplication',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('consumer_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='CONSUMER KEY')),
                ('consumer_secret', models.CharField(blank=True, max_length=100, null=True, verbose_name='CONSUMER SECRET')),
                ('gateway_entity_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='GATEWAY ENTITY ID')),
            ],
            options={
                'verbose_name': 'Aplicación',
                'verbose_name_plural': 'Aplicaciones',
                'db_table': 'wellsfargo_application',
                'permissions': (('add_wellsfargoapplication', 'Adicionar aplicaciones de Wells Fargo'), ('change_wellsfargoapplication', 'Editar aplicaciones de Wells Fargo'), ('view_wellsfargoapplication', 'Ver aplicaciones de Wells Fargo'), ('delete_wellsfargoapplication', 'Eliminar aplicaciones de Wells Fargo')),
                'default_permissions': [],
            },
            bases=('oauth2_provider.application',),
        ),
    ]
