# Generated by Django 4.2.2 on 2023-08-08 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellsfargoapplication',
            old_name='consumer_key',
            new_name='api_id',
        ),
        migrations.RenameField(
            model_name='wellsfargoapplication',
            old_name='consumer_secret',
            new_name='api_secret',
        ),
    ]
