# Generated by Django 4.2.2 on 2023-08-11 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0005_alter_accesstoken_user_alter_application_user_and_more'),
        ('applications', '0002_rename_consumer_key_wellsfargoapplication_api_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquaresApplication',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('application_id', models.CharField(max_length=255, null=True, verbose_name='ID de la Aplicacion')),
                ('location_id', models.CharField(max_length=100, null=True, verbose_name='ID de Localización')),
                ('access_token', models.CharField(max_length=255, verbose_name='Token de Acceso')),
                ('environment', models.CharField(choices=[('sandbox', 'sandbox'), ('production', 'production')], max_length=50, verbose_name='Entorno')),
            ],
            options={
                'verbose_name': 'Aplicación',
                'verbose_name_plural': 'Aplicaciones',
                'db_table': 'squares_application',
                'permissions': (('add_squaresapplication', 'Adicionar aplicaciones de Square'), ('change_squaresapplication', 'Editar aplicaciones de Square'), ('view_squaresapplication', 'Ver aplicaciones de Square'), ('delete_squaresapplication', 'Eliminar aplicaciones de Square')),
                'default_permissions': [],
            },
            bases=('oauth2_provider.application',),
        ),
        migrations.RemoveField(
            model_name='wellsfargoapplication',
            name='gateway_entity_id',
        ),
    ]
