# Generated by Django 4.2.2 on 2023-09-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_squaresapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellsfargoapplication',
            name='api_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='API LOGIN ID'),
        ),
        migrations.AlterField(
            model_name='wellsfargoapplication',
            name='api_secret',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TRANSACTION KEY'),
        ),
    ]
