# Generated by Django 4.2.2 on 2023-09-22 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0005_alter_accesstoken_user_alter_application_user_and_more'),
        ('applications', '0004_alter_wellsfargoapplication_api_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankOfAmericaApplication',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('merchant_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Merchant ID')),
                ('key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Key')),
                ('shared_secret_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shared secret key')),
                ('run_environment', models.CharField(choices=[('test', 'apitest.cybersource.com'), ('production', 'api.cybersource.com')], max_length=50, verbose_name='Entorno')),
            ],
            options={
                'verbose_name': 'Aplicación',
                'verbose_name_plural': 'Aplicaciones',
                'db_table': 'bankofamerica_application',
                'permissions': (('add_bankofamericaapplication', 'Adicionar aplicaciones de Bank of America'), ('change_bankofamericaapplication', 'Editar aplicaciones de Bank of America'), ('view_bankofamericaapplication', 'Ver aplicaciones de Bank of America'), ('delete_bankofamericaapplication', 'Eliminar aplicaciones de Bank of America')),
                'default_permissions': [],
            },
            bases=('oauth2_provider.application',),
        ),
    ]
