# Generated by Django 4.2.2 on 2023-09-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_bankofamericaapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankofamericaapplication',
            name='run_environment',
            field=models.CharField(choices=[('apitest.cybersource.com', 'test'), ('api.cybersource.com', 'production')], max_length=50, verbose_name='Entorno'),
        ),
    ]
