# Generated by Django 4.2.2 on 2023-08-03 18:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WellsFargoDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentation', ckeditor.fields.RichTextField(verbose_name='Documentación')),
            ],
            options={
                'verbose_name': 'Documentación',
                'verbose_name_plural': 'Documentación',
                'db_table': 'wellsfargo_documentation',
                'permissions': (('add_wellsfargodocumentation', 'Adicionar documentación de Wells Fargo'), ('change_wellsfargodocumentation', 'Editar documentación de Wells Fargo'), ('view_wellsfargodocumentation', 'Ver documentación de Wells Fargo'), ('delete_wellsfargodocumentation', 'Eliminar documentación de Wells Fargo')),
                'default_permissions': [],
            },
        ),
    ]
