# Generated by Django 4.2.2 on 2023-08-11 04:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquaresDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentation', ckeditor.fields.RichTextField(verbose_name='Documentación')),
            ],
            options={
                'verbose_name': 'Documentación',
                'verbose_name_plural': 'Documentación',
                'db_table': 'squares_documentation',
                'permissions': (('add_squaresdocumentation', 'Adicionar documentación de Square'), ('change_squaresdocumentation', 'Editar documentación de Square'), ('view_squaresdocumentation', 'Ver documentación de Square'), ('delete_squaresdocumentation', 'Eliminar documentación de Square')),
                'default_permissions': [],
            },
        ),
    ]
