from .application import ApplicationAdmin
from .wells_fargo_application import WellsFargoApplicationAdmin
from .wells_fargo_documentation import WellsFargoDocumentationAdmin
from .wells_fargo_payment import WellsFargoPaymentAdmin
from .square_application import SquareApplicationAdmin
from .square_documentation import SquareDocumentationAdmin
from .square_payment import SquarePaymentAdmin